---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: operator
  namespace: system
  labels:
    app.kubernetes.io/name: p-rmq-operator
    app.kubernetes.io/component: p-rmq-operator
    app.kubernetes.io/part-of: pivotal-rabbitmq
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: p-rmq-operator
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: p-rmq-operator
        app.kubernetes.io/component: p-rmq-operator
        app.kubernetes.io/part-of: pivotal-rabbitmq
    spec:
      containers:
      - command:
        - /manager
        image: controller:latest
        name: operator
        resources:
          limits:
            cpu: 200m
            memory: 500Mi
          requests:
            cpu: 200m
            memory: 500Mi
        env:
          - name: OPERATOR_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
      terminationGracePeriodSeconds: 10
