# Adds namespace to all resources.
namespace: rabbitmq-for-kubernetes-servicebroker

# Value of this field is prepended to the
# names of all resources, e.g. a deployment named
# "wordpress" becomes "alices-wordpress".
# Note that it should also match with the prefix (text before '-') of the namespace
# field above.
namePrefix: rabbitmq-for-kubernetes-

# Labels to add to all resources and selectors.
#commonLabels:
#  someName: someValue

# Each entry in this list must resolve to an existing
# resource definition in YAML.  These are the resource
# files that kustomize reads, modifies and emits as a
# YAML string, with resources separated by document
# markers ("---").
resources:
- ./rbac_role.yaml
- ./rbac_role_binding.yaml
- ./service.yaml
- ./replicaset.yaml

