apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/component: rabbitmq-cluster-operator
    app.kubernetes.io/name: pivotal-rabbitmq-system
    app.kubernetes.io/part-of: rabbitmq
  name: pivotal-rabbitmq-system
