---
apiVersion: v1
kind: ConfigMap
metadata:
  name: operator-config
  namespace: system
data:
  config: |
    service:
      type: "ClusterIP"
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "15692"
    image: "REPLACE-WITH-RABBITMQ-IMAGE-REFERENCE"
    imagePullSecret: ""
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: operator
  namespace: system
spec:
  template:
    spec:
      containers:
      - image: "REPLACE-WITH-OPERATOR-IMAGE-URL"
        name: operator
