---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: operator
  namespace: system
spec:
  template:
    spec:
      containers:
      - image: "REPLACE-WITH-OPERATOR-IMAGE-URL"
        name: operator
