---
apiVersion: v1
kind: ConfigMap
metadata:
  name: operator-config
  namespace: system
data:
  CONFIG: |
    SERVICE:
      TYPE: "ClusterIP"
    IMAGE_URL: "REPLACE-WITH-RABBITMQ-IMAGE-URL"
    IMAGE_PULL_SECRET: ""
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: operator
  namespace: system
spec:
  template:
    spec:
      containers:
      - image: "REPLACE-WITH-OPERATOR-IMAGE-URL"
        name: operator
