apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: perf-test
  name: perf-test
  namespace: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: perf-test
  template:
    metadata:
      labels:
        app: perf-test
    spec:
      containers:
      - image: pivotalrabbitmq/perf-test
        imagePullPolicy: Always
        name: perf-test
        # The URL structure is described here: https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#a-records
        args: ["--uri", "amqp://rabbitmq.rabbitmq.svc.cluster.local", "--rate", "1"]
