# Adds namespace to all resources.
namespace: pivotal-rabbitmq-system

# Value of this field is prepended to the
# names of all resources, e.g. a deployment named
# "wordpress" becomes "alices-wordpress".
# Note that it should also match with the prefix (text before '-') of the namespace
# field above.
namePrefix: p-rmq-

resources:
- service_account.yaml
- role.yaml
- role_binding.yaml
- leader_election_role.yaml
- leader_election_role_binding.yaml

patches:
# the following patch file adds labels to the operator ClusterRole definition in role.yaml
# role.yaml is a generated file, and adding labels directly to the file does not work.
- role_labels_patch.yaml
