apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: leader-election-rolebinding
  labels:
    app.kubernetes.io/name: p-rmq-operator
    app.kubernetes.io/component: p-rmq-operator
    app.kubernetes.io/part-of: pivotal-rabbitmq
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: leader-election-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: system
