# permissions for end users to view rabbitmqclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rabbitmqcluster-viewer-role
rules:
- apiGroups:
  - rabbitmq.com.rabbitmq.com
  resources:
  - rabbitmqclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - rabbitmq.com.rabbitmq.com
  resources:
  - rabbitmqclusters/status
  verbs:
  - get
