# permissions for end users to edit rabbitmqclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rabbitmqcluster-editor-role
rules:
- apiGroups:
  - rabbitmq.com.rabbitmq.com
  resources:
  - rabbitmqclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rabbitmq.com.rabbitmq.com
  resources:
  - rabbitmqclusters/status
  verbs:
  - get
