apiVersion: v1
kind: Service
metadata:
  name: servicebroker-lb
  namespace: rabbitmq-for-kubernetes-servicebroker
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: servicebroker
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
