apiVersion: v1
kind: Service
metadata:
  namespace: rabbitmq
  name: rabbitmq
  labels:
    app: rabbitmq
spec:
  selector:
    app: rabbitmq
  ports:
  - port: 5672
    name: amqp
    protocol: TCP # or UDP
  - port: 15672
    name: http
    protocol: TCP # or UDP
