---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq
  namespace: rabbitmq
  labels:
    app: rabbitmq
data:
  # If you edit the list of enabled plugins, you need to delete the pod for this change to take effect
  enabled_plugins: |-
    [rabbitmq_management, rabbitmq_peer_discovery_k8s, rabbitmq_federation, rabbitmq_federation_management].

  rabbitmq.conf: |
    cluster_formation.peer_discovery_backend  = rabbit_peer_discovery_k8s
    cluster_formation.k8s.host = kubernetes.default.svc.cluster.local
    cluster_formation.k8s.address_type = hostname
    default_user = admin
    default_pass = alwaysbekind
