---
resources:
# https://github.com/concourse/git-resource
- name: &repo rabbitmq-for-kubernetes
  type: git
  source:
    uri: git@github.com:pivotal/rabbitmq-for-kubernetes
    branch: master
    private_key: ((git-ssh-key))
# https://github.com/concourse/docker-image-resource
- name: &image rabbitmq-k8s-manager
  type: docker-image
  source:
    # https://github.com/concourse/docker-image-resource/pull/193#issuecomment-402865356
    repository: eu.gcr.io/cf-rabbitmq/rabbitmq-k8s-manager
    username: _json_key
    password: ((gcp-service-account-key))

jobs:
- name: test
  serial: true
  plan:
  - get: *repo
    trigger: true
  - task: unit
    tags:
    - k8s
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: golang
          tag: 1.12
      caches:
        - path: app_cache
        - path: go_cache
      inputs:
      - name: *repo
        path: /go/src/github.com/pivotal/rabbitmq-for-kubernetes
      outputs:
      - name: &docker_image_path docker_image_build
      params:
        # To use the right value for TERM, check what terms are available in the image: find /lib/terminfo -type f
        # To double-check that a specific term is available, run: infocmp xterm-256color
        TERM: xterm-256color
      run:
        path: sh
        args:
        - -exc
        - |
          set -eu
          export BUILD_PATH=$PWD
          export APP_CACHE_PATH=$BUILD_PATH/app_cache
          export GO_CACHE_PATH=$BUILD_PATH/go_cache
          export DOCKER_IMAGE_PATH=$BUILD_PATH/docker_image_build
          export GOPATH=$BUILD_PATH/go
          export PATH=$PATH:$GOPATH/bin
          cd $GOPATH/src/github.com/pivotal/rabbitmq-for-kubernetes
          [ -d $APP_CACHE_PATH/bin ] && mv $APP_CACHE_PATH/bin .
          [ -d $APP_CACHE_PATH/vendor ] && mv $APP_CACHE_PATH/vendor .
          [ -d $GO_CACHE_PATH/bin ] && mv $GO_CACHE_PATH/bin $GOPATH
          make test
          cp -r bin $APP_CACHE_PATH/
          cp -r vendor $APP_CACHE_PATH/
          cp -r $GOPATH/bin $GO_CACHE_PATH/
          cp -r pkg cmd vendor templates Dockerfile $DOCKER_IMAGE_PATH/
  # https://blog.scottlogic.com/2016/06/20/declarative-ci-cd-with-concourse.html
  - put: *image
    params:
      build: *docker_image_path
      tag_file: rabbitmq-for-kubernetes/.git/short_ref
