---
resource_types:
- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final

resources:
# https://github.com/concourse/git-resource
- name: &repo rabbitmq-for-kubernetes
  type: git
  source:
    uri: git@github.com:pivotal/rabbitmq-for-kubernetes
    branch: master
    private_key: |
      ((operator-git-ssh-key))

- name: rabbitmq-for-kubernetes-broker
  type: git
  source:
    uri: git@github.com:pivotal/rabbitmq-for-kubernetes-broker
    branch: master
    private_key: |
      ((broker-git-ssh-key))

# https://github.com/concourse/docker-image-resource
- name: &operator-image rabbitmq-k8s-operator
  type: docker-image
  source:
    repository: eu.gcr.io/cf-rabbitmq-for-k8s-bunny/rabbitmq-for-kubernetes-controller
    tag: latest
    username: _json_key
    password: ((gcr-push-service-account-key))

- name: every-friday
  type: time
  source:
    start: 8:00 AM
    stop: 9:00 AM
    days:
    - Friday
    location: Europe/London

- name: rabbitmq-for-kubernetes-pivnet
  type: pivnet
  source:
    api_token: ((pivnet-api-token))
    product_slug: p-rabbitmq-for-kubernetes
    access_key_id: ((pivnet-aws-access-key-id))
    secret_access_key: ((pivnet-aws-secret-access-key))

- name: product-release
  type: s3
  source:
    bucket: rabbitmq-for-kubernetes
    regexp: (.*).tar
    region_name: eu-west-1
    access_key_id: ((pivnet-aws-access-key-id))
    secret_access_key: ((pivnet-aws-secret-access-key))

- name: product-metadata
  type: s3
  source:
    bucket: rabbitmq-for-kubernetes
    regexp: (.*).yml
    region_name: eu-west-1
    access_key_id: ((pivnet-aws-access-key-id))
    secret_access_key: ((pivnet-aws-secret-access-key))

jobs:
- name: integration-tests
  serial: true
  plan:
  - get: *repo
    trigger: true
  - task: run-integration-tests
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          tag: latest
          repository: eu.gcr.io/cf-rabbitmq-for-k8s-bunny/rabbitmq-for-kubernetes-ci
          username: _json_key
          password: ((gcr-push-service-account-key))
      inputs:
      - name: *repo
        path: /go/src/github.com/pivotal/rabbitmq-for-kubernetes
      run:
        path: bash
        args:
        - -exc
        - |
          cd go/src/github.com/pivotal/rabbitmq-for-kubernetes
          echo "Running unit tests"
          make unit-tests
          echo "Running integration tests"
          make integration-tests

- name: build-operator
  serial: true
  plan:
  - get: *repo
    passed: [integration-tests]
    trigger: true
  - put: *operator-image
    params:
      build: *repo
      tag_file: rabbitmq-for-kubernetes/.git/short_ref

- name: operator-system-tests
  serial: true
  plan:
  - get: *repo
  - get: *operator-image
    passed: [build-operator]
    trigger: true
  - task: run-system-tests
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          tag: latest
          repository: eu.gcr.io/cf-rabbitmq-for-k8s-bunny/rabbitmq-for-kubernetes-ci
          username: _json_key
          password: ((gcr-pull-service-account-key))
      inputs:
      - name: *repo
        path: /go/src/github.com/pivotal/rabbitmq-for-kubernetes
      - name: *operator-image
        path: operator-image
      params:
        # To use the right value for TERM, check what terms are available in the image: find /lib/terminfo -type f
        # To double-check that a specific term is available, run: infocmp xterm-256color
        TERM: xterm-256color
        KUBECTL_SECRET_TOKEN: ((rmq-k8s-ci-kubectl-service-account-key))
        KUBECTL_SECRET_TOKEN_PATH: kubectl-secret-token.json
        GCR_VIEWER_KEY_CI: ((gcr-pull-service-account-key))
        K8S_OPERATOR_NAMESPACE: pivotal-rabbitmq-system-ci
      run:
        path: bash
        args:
        - -exc
        - |
          set +x
          echo "Outputting kubectl token to a file"
          echo -n $KUBECTL_SECRET_TOKEN > $KUBECTL_SECRET_TOKEN_PATH
          set -x

          export KUBECTL_SECRET_TOKEN_PATH=$PWD/$KUBECTL_SECRET_TOKEN_PATH
          cd go/src/github.com/pivotal/rabbitmq-for-kubernetes
          export CONTROLLER_IMAGE_TAG=$(cat .git/short_ref)
          echo "Deploying ci environment"
          make deploy-ci
          echo "Testing single node cluster..."
          make system-tests-ci

- name: broker-system-tests
  serial: true
  plan:
  - get: rabbitmq-for-kubernetes-broker
  - get: *repo
    passed: [operator-system-tests]
    trigger: true
  - task: run-broker-system-tests
    on_success:
      task: destroy-ci
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            tag: latest
            repository: eu.gcr.io/cf-rabbitmq-for-k8s-bunny/rabbitmq-for-kubernetes-ci
            username: _json_key
            password: ((gcr-push-service-account-key))
        inputs:
        - name: *repo
          path: /go/src/github.com/pivotal/rabbitmq-for-kubernetes
        params:
          # To use the right value for TERM, check what terms are available in the image: find /lib/terminfo -type f
          # To double-check that a specific term is available, run: infocmp xterm-256color
          TERM: xterm-256color
          KUBECTL_SECRET_TOKEN: ((rmq-k8s-ci-kubectl-service-account-key))
          KUBECTL_SECRET_TOKEN_PATH: kubectl-secret-token.json
        run:
          path: bash
          args:
          - -exc
          - |
            set +x
            echo "Outputting kubectl token to a file"
            echo -n $KUBECTL_SECRET_TOKEN > $KUBECTL_SECRET_TOKEN_PATH
            set -x
            export KUBECTL_SECRET_TOKEN_PATH=$PWD/$KUBECTL_SECRET_TOKEN_PATH
            cd go/src/github.com/pivotal/rabbitmq-for-kubernetes
            echo "Destroying ci environment"
            make destroy-ci
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          tag: latest
          repository: eu.gcr.io/cf-rabbitmq-for-k8s-bunny/rabbitmq-for-kubernetes-ci
          username: _json_key
          password: ((gcr-pull-service-account-key))
      inputs:
      - name: rabbitmq-for-kubernetes-broker
        path: /go/src/github.com/pivotal/rabbitmq-for-kubernetes-broker
      params:
        TERM: xterm-256color
        OPERATOR_PRIVATE_KEY: ((operator-git-ssh-key))
        KUBECTL_SECRET_TOKEN: ((rmq-k8s-ci-kubectl-service-account-key))
        KUBECTL_SECRET_TOKEN_PATH: kubectl-secret-token.json
        CI_CLUSTER: dev-bunny
        GCP_PROJECT: cf-rabbitmq-for-k8s-bunny
      run:
        path: bash
        args:
        - -exc
        - |
          # for accessing private repos
          git config --global url."git@github.com:".insteadOf "https://github.com/"
          # for trusting github.com without prompt
          mkdir -p ${HOME}/.ssh
          set +x
          echo "${OPERATOR_PRIVATE_KEY}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "Outputting kubectl token to a file"
          echo -n $KUBECTL_SECRET_TOKEN > $KUBECTL_SECRET_TOKEN_PATH
          set -x
          gcloud auth activate-service-account --key-file=${KUBECTL_SECRET_TOKEN_PATH}
          gcloud container clusters get-credentials ${CI_CLUSTER} --region europe-west1 --project ${GCP_PROJECT}
          ssh-keyscan -H github.com > ~/.ssh/known_hosts
          cd go/src/github.com/pivotal/rabbitmq-for-kubernetes-broker
          ginkgo -r integration_tests/

- name: renew-env
  serial: true
  plan:
  - get: every-friday
    trigger: true
  - task: renew-toolsmith-environment
    tags: [toolsmiths-shared-vsphere]
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          tag: latest
          repository: eu.gcr.io/cf-rabbitmq-for-k8s-bunny/rabbitmq-for-kubernetes-ci
          username: _json_key
          password: ((gcr-push-service-account-key))
      params:
        TOKEN: ((toolsmith-api-token))
      run:
        path: bash
        args:
        - -ec
        - |
          echo "curling https://environments.toolsmiths.cf-app.com/custom_gcp_environments/20/renew"
          curl -H "Authorization: OAuth ${TOKEN}" https://environments.toolsmiths.cf-app.com/custom_gcp_environments/20/renew

- name: upload-pivnet
  serial: true
  plan:
  - get: product-release
  - get: product-metadata
  - put: rabbitmq-for-kubernetes-pivnet
    params:
      s3_filepath_prefix: rabbitmq-for-kubernetes
      file_glob: product-release/rabbitmq-for-kubernetes-*.tar
      metadata_file: product-metadata/metadata.yml
