apiVersion: v1
kind: Service
metadata:
  labels:
    app: rabbitmqcluster-sample
  name: rabbitmqcluster-service
spec:
  ports:
  - name: amqp
    port: 5672
    protocol: TCP
    targetPort: 5672
  - name: http
    port: 15672
    protocol: TCP
    targetPort: 15672
  selector:
    app: rabbitmqcluster-sample
  sessionAffinity: None
  type: LoadBalancer
