
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: rabbitmqclusters.rabbitmq.pivotal.io
spec:
  additionalPrinterColumns:
  - JSONPath: .metadata.creationTimestamp
    name: Age
    type: date
  - JSONPath: .status.clusterStatus
    name: Status
    type: string
  group: rabbitmq.pivotal.io
  names:
    kind: RabbitmqCluster
    listKind: RabbitmqClusterList
    plural: rabbitmqclusters
    singular: rabbitmqcluster
  scope: ""
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: RabbitmqCluster is the Schema for the rabbitmqclusters API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: RabbitmqClusterSpec defines the desired state of RabbitmqCluster
          properties:
            image:
              type: string
            imagePullSecret:
              type: string
            persistence:
              properties:
                storage:
                  type: string
                storageClassName:
                  type: string
              type: object
            replicas:
              enum:
              - 1
              - 3
              type: integer
            resource:
              properties:
                limit:
                  properties:
                    cpu:
                      pattern: ^([+-]?[0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$
                      type: string
                    memory:
                      pattern: ^([+-]?[0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$
                      type: string
                  type: object
                request:
                  properties:
                    cpu:
                      pattern: ^([+-]?[0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$
                      type: string
                    memory:
                      pattern: ^([+-]?[0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$
                      type: string
                  type: object
              type: object
            service:
              properties:
                annotations:
                  additionalProperties:
                    type: string
                  type: object
                type:
                  enum:
                  - ClusterIP
                  - LoadBalancer
                  - NodePort
                  type: string
              type: object
          required:
          - replicas
          type: object
        status:
          description: RabbitmqClusterStatus defines the observed state of RabbitmqCluster
          properties:
            clusterStatus:
              type: string
          type: object
      type: object
  version: v1beta1
  versions:
  - name: v1beta1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
