name: rabbitmq
version: 0.1
appVersion: 3.8.3
description: Pivotal RabbitMQ for Kubernetes
keywords:
- rabbitmq
- message queue
- AMQP
home: https://pivotal.io/rabbitmq
icon: https://bitnami.com/assets/stacks/rabbitmq/img/rabbitmq-stack-220x234.png
maintainers:
- name: Pivotal
  email: rabbitmq-for-k8s@pivotal.com
engine: gotpl
